# Comparação entre Tensorflow 1 e Tensorflow 2

## Tensorflow 1

In [9]:
#!pip uninstall -y tensorflow
#Comando necessário, pois o TensorFlow-gpu não 
#desinstala a versão mais recente do Tensorflow, pode gerar conflito

In [10]:
!pip install tensorflow-gpu==1.15

  Using cached https://files.pythonhosted.org/packages/bc/72/d06017379ad4760dc58781c765376ce4ba5dcf3c08d37032eeefbccf1c51/tensorflow_gpu-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/1e/e9/d3d747a97f7188f48aa5eda486907f3b345cd409f0a0850468ba867db246/tensorboard-1.15.0-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/de/62/2ee9cd74c9fa2fa450877847ba560b260f5d0fb70ee0595203082dafcc9d/tensorflow_estimator-1.15.1-py2.py3-none-any.whl
  Found existing installation: tensorboard 2.0.2
    Uninstalling tensorboard-2.0.2:
      Successfully uninstalled tensorboard-2.0.2
  Found existing installation: tensorflow-estimator 2.0.1
    Uninstalling tensorflow-estimator-2.0.1:
      Successfully uninstalled tensorflow-estimator-2.0.1
  Found existing installation: tensorflow-gpu 2.0.0
    Uninstalling tensorflow-gpu-2.0.0:
      Successfully uninstalled tensorflow-gpu-2.0.0


In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'1.15.0'

### Constantes

#### Definindo as constantes

In [13]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [14]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [15]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

ValueError: ignored

#### Acessando os valores de uma constante

In [16]:
session = tf.Session()

In [17]:
session.run(tf.global_variables_initializer())

In [18]:
tensor_value = session.run(tensor)

In [19]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variáveis


#### Definindo uma variável


In [20]:
#Definindo uma variável no Tensorflow
variavel = tf.Variable([[30,20],[10,45]])

In [21]:
variavel

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [22]:
variavel.eval()
#se não iniciar a sessão, não dá pra acessar os valores no Tensorflow1 
#no Tensorflow2 não precisa iniciar sessão

ValueError: ignored

#### Acessando os valores de uma variável

In [23]:
#Iniciando a sessão
session = tf.Session()

In [24]:
# Iniciando todas as variáveis da sessão
session.run(tf.global_variables_initializer())

In [25]:
# Executando o método eval no ambiente com a sessão inicializada para constante 
variavel.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## Tensorflow 2.0

### Instalando o TensorFlow 2.0

In [28]:
! pip install tensorflow-gpu==2.0.0

  Using cached https://files.pythonhosted.org/packages/a1/eb/bc0784af18f612838f90419cf4805c37c20ddb957f5ffe0c42144562dcfa/tensorflow_gpu-2.0.0-cp37-cp37m-manylinux2010_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/76/54/99b9d5d52d5cb732f099baaaf7740403e83fe6b0cedde940fabd2b13d75a/tensorboard-2.0.2-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow-gpu 1.15.0
    Uninstalling tensorflow-gpu-1.15.0:
      Successfully uninstalled tensorflow-gpu-1.15.0


In [1]:
import tensorflow as tf 
import numpy as np

In [3]:
tf.__version__

'2.0.0'

### Constantes

#### Definindo uma constante

In [4]:
tensor_20 = tf.constant([[23,4],[32,51]])

In [5]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [8]:
#Acessando valores do tensor com numpy
#Não precisa iniciar a sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [11]:
#Convertendo um numpy para um tensor do TensorFlow
numpy_tensor = np.array([[23,4],[32,51]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: id=2, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variáveis

#### Definindo uma variável

In [14]:
tf2_variavel = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variavel
# a diferença do ponto e sem ponto 
  # com ponto se torna um float e sem, um inteiro

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [15]:
tf2_variavel.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [16]:
tf2_variavel[0,2].assign(100)
tf2_variavel

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

#### Operações com tensores

In [18]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: id=40, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição

In [19]:
tensor + 2

<tf.Tensor: id=42, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicação

In [20]:
tensor * 5 

<tf.Tensor: id=44, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando função do numpy nos tensores do TensoFlow

In [21]:
np.square(tensor) #quadrado de todos os membros dos tensores

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [22]:
np.sqrt(tensor) # raiz quadrada de todos os membros dos tensores

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [23]:
np.dot(tensor, tensor_20) #produto escalar dos dois tensores

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

In [24]:
tf_string = tf.constant("Tensorflow")
tf_string

<tf.Tensor: id=45, shape=(), dtype=string, numpy=b'Tensorflow'>

#### Operações simples com strings

In [25]:
tf.strings.length(tf_string) #numpy = 10 (tamanho da string)

<tf.Tensor: id=46, shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string,"UTF8")

<tf.Tensor: id=50, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

#### Armazenando vetores com strings

In [29]:
tf_s_array = tf.constant(["Ana","Joana","Amelia"])
for string in tf_s_array:
  print(string)
  print(tf.strings.length(string))

tf.Tensor(b'Ana', shape=(), dtype=string)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(b'Joana', shape=(), dtype=string)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(b'Amelia', shape=(), dtype=string)
tf.Tensor(6, shape=(), dtype=int32)
